version: '3.4'

services:
  apitest:
    image: apitest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8675:8675
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
